### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by stonefishy** [SbstnErhrdt/node-port-test#1]
Hi SbstnErhrdt,

I'm a developer from china, currently is playing pi-network, I love this project and want to be a developer and do some contribution for Pi platform and related apps. I already submit a form to apply for as a developer from Pi application and official website. But didn't get any response.

I'm not sure if you're correct person, but I find you from the Pi desktop application docker instance, the docker instance source code is from your github repo and use for pi node ports listen testing. And from your profile, seems you also from Stanford.

If you can help me to be a contributor as developer for Pi ecosphere. That's much helpful. My email address is *andrewsy@live.com*

Thanks,
Andrew

**Comment by SbstnErhrdt** [comment]
Hi Andrew,

Thank you for your interest in the project.

I have helped them when I was in Stanford, but at the moment I do not have an active role. Therefore,  I will forward your request to Nicolas the Head of Technology of pi.  

Greetings
Seb

**Comment by stonefishy** [comment]
Hi Seb,

Great, Kindly thank you for your reply. 

Cheers,
Andrew
